### ISSUE TITLE
self.items_list clear after succesful send

### ISSUE THREAD

**Issue by skinkie** [jbfavre/python-zabbix#3]
I would expect that Datacontainer.items_list would be cleared after a succesfull sending. So the datacontainer can be reused.

**Comment by jbfavre** [comment]
Would you mind sharing a long running process you use ?
That would allow me to test protobix with your running condition.

**Comment by skinkie** [comment]
In definitely :)

**Comment by jbfavre** [comment]
OK. Waiting for it then.
I shall use it to write some tests as well :)

**Comment by skinkie** [comment]
Especially a test for send: success, connection failure, success.

**Comment by jbfavre** [comment]
Yep, that's the idea.
Don't know yet wether I will implement a zbabix trapper server for that purpose or rely on external existing Zabbix-server or not.
Since I'm still not that confortable with Python programming, I guess second choice is better, because simplier :)

**Comment by jbfavre** [comment]
Moved to jbfavre/python-protobix#1
